comments_min_spaces_from_content = 2
comments_require_starting_space = true
explicit_start = false
sequence_style = "block_style"
indent_mapping = 2
indent_offset = 2
indent_sequence = 4
line_length = 180
none_representation = "null"
quote_basic_values = false
quote_keys_and_basic_values = false
preserve_quotes = true
whitelines = 1  # allow keeping one empty line
