extends: default
yaml-files:
  - '*.yaml'
  - '*.yml'
ignore: |
  venv/
  .meltano/
  src/transform/dbt_packages/
  argo/out/
rules:
  brackets:
    forbid: non-empty
    max-spaces-inside-empty: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  document-end: disable
  document-start: disable
  empty-lines:
    max: 1
  indentation:
    indent-sequences: true
    spaces: 2
  line-length:
    max: 200
    allow-non-breakable-words: true
  truthy:
    check-keys: false
